import { HomePage } from "@frontEnd/container/HomePage";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

const AllEvents = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
        <ToastContainer position="top-left" autoClose={3000} theme="dark" />
      </main>
    </>
  );
};

export default AllEvents;
